{
 "title": "Dashboard - Exercices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total exercices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT COUNT(*) AS total_exercises\r\nFROM exercises;"
    }
   ]
  },
  {
   "title": "Exercices par niveau de difficulté ",
   "type": "barchart",
   "description": "On compte combien d'exercices existent pour chaque niveau avec la colonne difficulty_level et unknown sert a regrouper les valeurs vides",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  COALESCE(NULLIF(difficulty_level, ''), 'unknown') AS difficulty_level,\r\n  COUNT(*) AS total_exercises\r\nFROM exercises\r\nGROUP BY 1\r\nORDER BY total_exercises DESC;"
    }
   ]
  },
  {
   "title": "Répartition par types d'exercices",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT coalesce(NULLIF(type, ''), 'unknown') as type,\r\n count(*) as total_exercices\r\nFROM exercises \r\nGROUP BY 1\r\nORDER BY total_exercices DESC;\r\n"
    }
   ]
  }
 ]
}