{
 "title": "Dashboard - Foods",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total aliments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT count(*) as total_foods from foods;"
    }
   ]
  },
  {
   "title": "Moyenne des macros aliments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  ROUND(AVG(calories)::numeric, 2) AS avg_calories,\r\n  ROUND(AVG(protein)::numeric, 2) AS avg_protein,\r\n  ROUND(AVG(fat)::numeric, 2) AS avg_fat,\r\n  ROUND(AVG(carbohydrates)::numeric, 2) AS avg_carbohydrates,\r\n  ROUND(AVG(fiber)::numeric, 2) AS avg_fiber,\r\n  ROUND(AVG(sugars)::numeric, 2) AS avg_sugars,\r\n  ROUND(AVG(sodium)::numeric, 2) AS avg_sodium\r\nFROM foods;"
    }
   ]
  },
  {
   "title": "Répartitions par catégorie des aliments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  COALESCE(NULLIF(category, ''), 'unknown') AS category,\r\n  COUNT(*) AS total_foods\r\nFROM foods\r\nGROUP BY 1\r\nORDER BY total_foods DESC;"
    }
   ]
  }
 ]
}