{
 "title": "Dashboard - Health metrics",
 "time": { "from": "2026-03-10T00:00:00.000Z", "to": "2026-04-09T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total health metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT COUNT(*) AS total_health_metrics\r\nFROM health_metrics;"
    }
   ]
  },
  {
   "title": "Valeurs hors plage health_metrics",
   "type": "gauge",
   "description": "Calcul de pourcentage de lignes avec des valeurs impossibles. (bpm trop haut, poids <= 0)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT ROUND(100.0 * SUM(\r\n      CASE WHEN\r\n        (steps_count < 0)\r\n        OR (current_weight <= 0)\r\n        OR (avg_bpm < 30 OR avg_bpm > 220)\r\n        OR (max_bpm < 30 OR max_bpm > 250)\r\n        OR (active_minute < 0 OR active_minute > 1440)\r\n        OR (calories_burned < 0)\r\n      THEN 1 ELSE 0 END\r\n    ) / NULLIF(COUNT(*),0),\r\n    2\r\n  ) AS value\r\nFROM health_metrics;"
    }
   ]
  },
  {
   "title": "Top workout type ",
   "type": "barchart",
   "description": "Compte combien d'enregistrement existent dans workout_type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  workout_type AS category,\r\n  COUNT(*) AS value\r\nFROM health_metrics\r\nWHERE workout_type IS NOT NULL AND workout_type <> ''\r\nGROUP BY 1\r\nORDER BY value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Calories brûlées moyennes par jour",
   "type": "timeseries",
   "description": "vérifier le flux de données des activité et efforts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT date_trunc('day', date) as time, \r\n  avg(calories_burned) as calories_burned\r\nFROM health_metrics \r\nWHERE date is NOT NULL and calories_burned is NOT NULL\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Utilisateurs actifs par jour ",
   "type": "timeseries",
   "description": "Compte combien l'utilisateur est actif",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  date_trunc('day', date) AS time,\r\n  COUNT(DISTINCT user_id) AS active_users\r\nFROM health_metrics\r\nWHERE date IS NOT NULL AND active_minute <= 30\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  }
 ]
}