{
 "title": "Dashboard - Users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total utilisateurs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "laravel", "rawSql": "SELECT count(*) from users;" }
   ]
  },
  {
   "title": "Répartition par tranches d'âges",
   "type": "barchart",
   "description": "On calcule l'âge à partir du birthdate, puis on regroupe les utilisateurs en tranches (18-24, 25-34 ..) afin d'obtenir une segmentation lisibles. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) < 18 THEN '<18'\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) BETWEEN 18 AND 24 THEN '18-24'\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) BETWEEN 25 AND 34 THEN '25-34'\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) BETWEEN 35 AND 44 THEN '35-44'\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) BETWEEN 45 AND 54 THEN '45-54'\r\n    WHEN EXTRACT(YEAR FROM age(birthdate)) BETWEEN 55 AND 64 THEN '55-64'\r\n    ELSE '65+'\r\n  END AS age_group,\r\n  COUNT(*) AS total_users\r\nFROM users\r\nWHERE birthdate IS NOT NULL\r\nGROUP BY age_group\r\nORDER BY age_group;"
    }
   ]
  },
  {
   "title": "Répartition par abonnement ",
   "type": "barchart",
   "description": "KPIs Business",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "laravel",
     "rawSql": "SELECT\r\n  COALESCE(NULLIF(subscription, ''), 'unknown') AS subscription,\r\n  COUNT(*) AS total_users\r\nFROM users\r\nGROUP BY 1\r\nORDER BY total_users DESC;"
    }
   ]
  }
 ]
}